"""fix chat model relationships

Revision ID: 18876b64a2e0
Revises: 8f8170007b4f
Create Date: 2025-07-30 02:27:50.757085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18876b64a2e0'
down_revision: Union[str, Sequence[str], None] = '8f8170007b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add progress_id as nullable first to avoid issues with existing data
    op.add_column('achievements', sa.Column('progress_id', sa.Integer(), nullable=True))
    
    # Update existing achievements to link to progress records
    # This assumes each user has a progress record
    op.execute("""
        UPDATE achievements 
        SET progress_id = (
            SELECT p.id 
            FROM progress p 
            WHERE p.athlete_id = achievements.athlete_id
        )
        WHERE progress_id IS NULL
    """)
    
    # Now make it non-nullable
    op.alter_column('achievements', 'progress_id', nullable=False)
    
    # Create foreign key
    op.create_foreign_key(None, 'achievements', 'progress', ['progress_id'], ['id'])
    
    # Update push_tokens structure
    op.add_column('push_tokens', sa.Column('token', sa.String(), nullable=False))
    op.add_column('push_tokens', sa.Column('device_info', sa.JSON(), nullable=True))
    op.add_column('push_tokens', sa.Column('last_used', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'push_tokens', ['token'])
    op.drop_column('push_tokens', 'device_token')
    
    # Update tournament_participations
    op.add_column('tournament_participations', sa.Column('age_category', sa.String(), nullable=True))
    op.add_column('tournament_participations', sa.Column('belt_category', sa.String(), nullable=True))
    op.add_column('tournament_participations', sa.Column('final_position', sa.Integer(), nullable=True))
    op.add_column('tournament_participations', sa.Column('registration_date', sa.DateTime(), nullable=True))
    op.add_column('tournament_participations', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('tournament_participations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('tournament_participations', 'belt_division')
    
    # Update server defaults for various columns (keeping the safe ones)
    op.alter_column('achievements', 'points_earned',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('achievements', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('achievements', 'achieved_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('achievements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    # Update chat-related defaults
    op.alter_column('chat_memberships', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_memberships', 'is_moderator',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_memberships', 'can_post',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_memberships', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_memberships', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    # Update chat messages defaults
    op.alter_column('chat_messages', 'message_type',
               existing_type=postgresql.ENUM('text', 'image', 'file', 'announcement', name='messagetype'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_messages', 'is_edited',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_messages', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_messages', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    # Update chat rooms defaults
    op.alter_column('chat_rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_rooms', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_rooms', 'is_moderated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    # Update forum defaults
    op.alter_column('forum_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_categories', 'is_moderated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_categories', 'min_role_to_post',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('forum_replies', 'is_edited',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_replies', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_replies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_replies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('forum_topics', 'views_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_topics', 'replies_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_topics', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_topics', 'is_locked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_topics', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('forum_topics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    # Update other table defaults
    op.alter_column('message_reactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('notification_templates', 'default_priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='notificationpriority'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notification_templates', 'is_push_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notification_templates', 'is_email_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notification_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notification_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('notifications', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='notificationpriority'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notifications', 'is_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('product_collections', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product_collections', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product_collections', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product_collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product_collections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('product_variants', 'price_adjustment',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product_variants', 'stock_quantity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product_variants', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product_variants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product_variants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('products', 'currency',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'status',
               existing_type=postgresql.ENUM('active', 'discontinued', 'out_of_stock', 'coming_soon', name='productstatus'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'has_variants',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('progress', 'current_belt',
               existing_type=postgresql.ENUM('white', 'yellow', 'orange', 'green', 'blue', 'brown', 'black', 'mixed', 'purple', 'juvenile_white', 'juvenile_grey', 'juvenile_yellow', 'juvenile_orange', 'juvenile_green', name='beltlevel'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('progress', 'current_stripes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('progress', 'total_classes_attended',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('progress', 'total_tournaments_participated',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('progress', 'total_wins',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('progress', 'total_losses',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('push_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('push_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('push_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('tournament_participations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('tournaments', 'tournament_level',
               existing_type=postgresql.ENUM('local', 'regional', 'national', 'international', name='tournamentlevel'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tournaments', 'status',
               existing_type=postgresql.ENUM('upcoming', 'ongoing', 'completed', 'cancelled', name='tournamentstatus'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tournaments', 'current_participants',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tournaments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tournaments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    
    op.alter_column('users', 'is_head_coach',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_head_coach',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('tournaments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('tournaments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('tournaments', 'current_participants',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('tournaments', 'status',
               existing_type=postgresql.ENUM('upcoming', 'ongoing', 'completed', 'cancelled', name='tournamentstatus'),
               server_default=sa.text("'upcoming'::tournamentstatus"),
               existing_nullable=True)
    op.alter_column('tournaments', 'tournament_level',
               existing_type=postgresql.ENUM('local', 'regional', 'national', 'international', name='tournamentlevel'),
               server_default=sa.text("'local'::tournamentlevel"),
               existing_nullable=True)
    op.add_column('tournament_participations', sa.Column('belt_division', postgresql.ENUM('white', 'yellow', 'orange', 'green', 'blue', 'brown', 'black', 'mixed', 'purple', 'juvenile_white', 'juvenile_grey', 'juvenile_yellow', 'juvenile_orange', 'juvenile_green', name='beltlevel'), autoincrement=False, nullable=True))
    op.alter_column('tournament_participations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_column('tournament_participations', 'updated_at')
    op.drop_column('tournament_participations', 'is_paid')
    op.drop_column('tournament_participations', 'registration_date')
    op.drop_column('tournament_participations', 'final_position')
    op.drop_column('tournament_participations', 'belt_category')
    op.drop_column('tournament_participations', 'age_category')
    op.add_column('push_tokens', sa.Column('device_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'push_tokens', type_='unique')
    op.alter_column('push_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('push_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('push_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.drop_column('push_tokens', 'last_used')
    op.drop_column('push_tokens', 'device_info')
    op.drop_column('push_tokens', 'token')
    op.alter_column('progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('progress', 'total_losses',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('progress', 'total_wins',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('progress', 'total_tournaments_participated',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('progress', 'total_classes_attended',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('progress', 'current_stripes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('progress', 'current_belt',
               existing_type=postgresql.ENUM('white', 'yellow', 'orange', 'green', 'blue', 'brown', 'black', 'mixed', 'purple', 'juvenile_white', 'juvenile_grey', 'juvenile_yellow', 'juvenile_orange', 'juvenile_green', name='beltlevel'),
               server_default=sa.text("'white'::beltlevel"),
               existing_nullable=True)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('products', 'has_variants',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('products', 'status',
               existing_type=postgresql.ENUM('active', 'discontinued', 'out_of_stock', 'coming_soon', name='productstatus'),
               server_default=sa.text("'active'::productstatus"),
               existing_nullable=True)
    op.alter_column('products', 'currency',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'KZT'::character varying"),
               existing_nullable=True)
    op.alter_column('product_variants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('product_variants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('product_variants', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('product_variants', 'stock_quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('product_variants', 'price_adjustment',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('product_collections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('product_collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('product_collections', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('product_collections', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('product_collections', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('notifications', 'is_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('notifications', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='notificationpriority'),
               server_default=sa.text("'normal'::notificationpriority"),
               existing_nullable=True)
    op.alter_column('notification_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('notification_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('notification_templates', 'is_email_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('notification_templates', 'is_push_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('notification_templates', 'default_priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='notificationpriority'),
               server_default=sa.text("'normal'::notificationpriority"),
               existing_nullable=True)
    op.alter_column('message_reactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('forum_topics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('forum_topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('forum_topics', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('forum_topics', 'is_locked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('forum_topics', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('forum_topics', 'replies_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('forum_topics', 'views_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('forum_replies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('forum_replies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('forum_replies', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('forum_replies', 'is_edited',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('forum_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('forum_categories', 'min_role_to_post',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'athlete'::character varying"),
               existing_nullable=True)
    op.alter_column('forum_categories', 'is_moderated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('forum_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('forum_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'is_moderated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('chat_messages', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('chat_messages', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('chat_messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('chat_messages', 'is_edited',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('chat_messages', 'message_type',
               existing_type=postgresql.ENUM('text', 'image', 'file', 'announcement', name='messagetype'),
               server_default=sa.text("'text'::messagetype"),
               existing_nullable=True)
    op.alter_column('chat_memberships', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('chat_memberships', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('chat_memberships', 'can_post',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('chat_memberships', 'is_moderator',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('chat_memberships', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.alter_column('achievements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('achievements', 'achieved_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('achievements', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('achievements', 'points_earned',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_column('achievements', 'progress_id')
    # ### end Alembic commands ###
