"""add_notifications_and_merchandise_systems

Revision ID: 4961fb10cf7a
Revises: 58e1bf012bef
Create Date: 2025-07-29 12:32:10.640411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4961fb10cf7a'
down_revision: Union[str, Sequence[str], None] = '58e1bf012bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
