"""add_progress_tracking_with_dual_belt_systems

Revision ID: 58e1bf012bef
Revises: adc2ea877fa9
Create Date: 2025-07-29 12:20:32.301250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e1bf012bef'
down_revision: Union[str, Sequence[str], None] = 'adc2ea877fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
