"""fix_models_import_and_create_missing_tables

Revision ID: 5d818c16ec6a
Revises: 4961fb10cf7a
Create Date: 2025-07-29 12:33:30.898058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d818c16ec6a'
down_revision: Union[str, Sequence[str], None] = '4961fb10cf7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
