"""Remove martial arts enum, grappling club only

Revision ID: 98285233d90a
Revises: a5b8921797bf
Create Date: 2025-07-26 00:15:21.050457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98285233d90a'
down_revision: Union[str, Sequence[str], None] = 'a5b8921797bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'martial_art')
    # userrole enum уже существует, не нужно создавать заново
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('martial_art', postgresql.ENUM('bjj', 'judo', 'wrestling', 'boxing', 'mma', 'kickboxing', name='martialarttype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
