"""Add individual training requests

Revision ID: adc2ea877fa9
Revises: f765b97c6cff
Create Date: 2025-07-29 12:12:00.789630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc2ea877fa9'
down_revision: Union[str, Sequence[str], None] = 'f765b97c6cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_training_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_parent_id', sa.Integer(), nullable=True),
    sa.Column('requested_date', sa.DateTime(), nullable=False),
    sa.Column('preferred_time_start', sa.String(), nullable=True),
    sa.Column('preferred_time_end', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'completed', name='individualtrainingstatus'), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_time_start', sa.String(), nullable=True),
    sa.Column('scheduled_time_end', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_amount', sa.Integer(), nullable=True),
    sa.Column('athlete_notes', sa.String(), nullable=True),
    sa.Column('coach_notes', sa.String(), nullable=True),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_training_requests_id'), 'individual_training_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_individual_training_requests_id'), table_name='individual_training_requests')
    op.drop_table('individual_training_requests')
    # ### end Alembic commands ###
