"""fix forum models ambiguous foreign keys

Revision ID: db003d9213aa
Revises: 18876b64a2e0
Create Date: 2025-07-30 02:39:41.780652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db003d9213aa'
down_revision: Union[str, Sequence[str], None] = '18876b64a2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_memberships_room_id_user_id_key'), 'chat_memberships', type_='unique')
    op.drop_index(op.f('ix_chat_messages_room_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_forum_replies_topic_id'), table_name='forum_replies')
    op.drop_index(op.f('ix_forum_topics_category_id'), table_name='forum_topics')
    op.drop_constraint(op.f('fk_forum_topics_last_reply'), 'forum_topics', type_='foreignkey')
    op.drop_column('forum_topics', 'last_reply_id')
    op.drop_constraint(op.f('message_reactions_message_id_user_id_emoji_key'), 'message_reactions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('message_reactions_message_id_user_id_emoji_key'), 'message_reactions', ['message_id', 'user_id', 'emoji'], postgresql_nulls_not_distinct=False)
    op.add_column('forum_topics', sa.Column('last_reply_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_forum_topics_last_reply'), 'forum_topics', 'forum_replies', ['last_reply_id'], ['id'])
    op.create_index(op.f('ix_forum_topics_category_id'), 'forum_topics', ['category_id'], unique=False)
    op.create_index(op.f('ix_forum_replies_topic_id'), 'forum_replies', ['topic_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_room_id'), 'chat_messages', ['room_id'], unique=False)
    op.create_unique_constraint(op.f('chat_memberships_room_id_user_id_key'), 'chat_memberships', ['room_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
